apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/warm-melody-260208/decentninja
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ./k8s*
